config/routes.rb
Rails.application.routes.draw do
  resources :products
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, through: :product_categories
  has_many :product_categories
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_categories
  has_many :categories, through: :product_categories
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @product = Product.all
  end
  def show
    @product = Product.find(params[:id])
  end
  private
  def product_params
    params.require(:product).permit(:id, :title, :description, :author, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geek Book Store</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="js/jquery.min.js"></script>
  <!-- Custom Theme files -->
  <!--theme-style-->
  <link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
  <!--//theme-style-->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="keywords" content="Mattress Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
         Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
  <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
  <!--fonts-->
  <link href='//fonts.googleapis.com/css?family=Lato:100,300,400,700,900' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'>
  <!--//fonts-->
  <!-- start menu -->
  <link href="css/memenu.css" rel="stylesheet" type="text/css" media="all" />
  <script type="text/javascript" src="js/memenu.js"></script>
  <script>$(document).ready(function(){$(".memenu").memenu();});</script>
  <script src="js/simpleCart.min.js"> </script>
</head>
<body>
<!--header-->
<div class="header">
  <div class="header-top">
    <div class="container">
      <div class="social">
        <ul>
          <li><a href="#"><i class="facebok"> </i></a></li>
          <li><a href="#"><i class="twiter"> </i></a></li>
          <li><a href="#"><i class="inst"> </i></a></li>
          <li><a href="#"><i class="goog"> </i></a></li>
          <div class="clearfix"></div>
        </ul>
      </div>
      <div class="header-left">
        <div class="search-box">
          <div id="sb-search" class="sb-search">
            <form action="#" method="post">
              <input class="sb-search-input" placeholder="Enter your search term..." type="search"  id="search">
              <input class="sb-search-submit" type="submit" value="">
              <span class="sb-icon-search"> </span>
            </form>
          </div>
        </div>
        <!-- search-scripts -->
        <script src="js/classie.js"></script>
        <script src="js/uisearch.js"></script>
        <script>
            new UISearch( document.getElementById( 'sb-search' ) );
        </script>
        <!-- //search-scripts -->
        <div class="ca-r">
          <div class="cart box_1">
            <a href="checkout.html">
              <h3>
                <div class="total">
                  <span class="simpleCart_total"></span>
                </div>
                <img src="images/cart.png" alt=""/>
              </h3>
            </a>
            <p><a href="javascript:;" class="simpleCart_empty">Empty Cart</a></p>
          </div>
        </div>
        <div class="clearfix"> </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="head-top">
      <div class="logo">
        <h1><a href="index.html">geekbook</a></h1>
      </div>
      <div class=" h_menu4">
        <ul class="memenu skyblue">
          <li>
            <a class="color1" href="#">PRORAMMING</a>
            <div class="mepanel">
              <div class="row">
                <div class="col1">
                  <div class="h_nav">
                    <ul>
                      <li><a href="products.html">Ruby</a></li>
                      <li><a href="products.html">Ruby on Rails</a></li>
                      <li><a href="products.html">NodeJS</a></li>
                      <li><a href="products.html">Angular</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="grid">
            <a class="color2" href="#">DESIGN</a>
            <div class="mepanel">
              <div class="row">
                <div class="col1">
                  <div class="h_nav">
                    <ul>
                      <li><a href="products.html">Adobe Ilustrator</a></li>
                      <li><a href="products.html">Adobe Photoshop</a></li>
                    </ul>
                  </div>
                </div>
          </li>
          <li><a class="color4" href="login.html">Login</a></li>
          <li><a class="color6" href="contact.html">Contact</a></li>
        </ul>
      </div>
    </div>
    <div class="clearfix"> </div>
  </div>
</div>
</div>
<%= yield %>
<div class="footer w3layouts">
  <div class="container">
    <div class="footer-top-at w3">

      <div class="col-md-3 amet-sed w3l">
        <h4>MORE INFO</h4>
        <ul class="nav-bottom">
          <li><a href="#">How to order</a></li>
          <li><a href="#">FAQ</a></li>
          <li><a href="contact.html">Location</a></li>
          <li><a href="#">Shipping</a></li>
          <li><a href="#">Membership</a></li>
        </ul>
      </div>
      <div class="col-md-3 amet-sed w3ls">
        <h4>CATEGORIES</h4>
        <ul class="nav-bottom">
          <li><a href="#">Bed linen</a></li>
          <li><a href="#">Cushions</a></li>
          <li><a href="#">Duvets</a></li>
          <li><a href="#">Pillows</a></li>
          <li><a href="#">Protectors</a></li>
        </ul>

      </div>
      <div class="col-md-3 amet-sed agileits">
        <h4>NEWSLETTER</h4>
        <div class="stay agileinfo">
          <div class="stay-left wthree">
            <form action="#" method="post">
              <input type="text" placeholder="Enter your email " required="">
            </form>
          </div>
          <div class="btn-1 w3-agileits">
            <form action="#" method="post">
              <input type="submit" value="Subscribe">
            </form>
          </div>
          <div class="clearfix"> </div>
        </div>

      </div>
      <div class="col-md-3 amet-sed agileits-w3layouts">
        <h4>CONTACT US</h4>
        <p>Contrary to popular belief</p>
        <p>The standard chunk</p>
        <p>office :  +12 34 995 0792</p>
      </div>
      <div class="clearfix"> </div>
    </div>
  </div>
  <div class="footer-class w3-agile">
    <p>© 2015 Mattress . All Rights Reserved | Design by  <a href="http://w3layouts.com/" target="_blank">W3layouts</a> </p>
  </div>
</div>
</body>
</html>

app/views/products/_product.html.erb
<div class="col-md-3 grid-top simpleCart_shelfItem">
  <a href="single.html" class="b-link-stripe b-animate-go  thickbox">
    <img class="img-responsive">
    <div class="b-wrapper">
      <h3 class="b-animate b-from-left    b-delay03 ">
        <span> <%= link_to product.title, product_path(product) %></span>
      </h3>
    </div>
  </a>
  <p><%= link_to product.title, product_path(product) %></p>
  <a href="#" class="item_add">
    <p class="number item_price"><i></i><%= number_to_currency(product.price, unit: "грн.", format: '%n %u') %></p>
  </a>
</div>

app/views/products/index.html.erb
<div class="banner">
  <div class="container">
    <script src="js/responsiveslides.min.js"></script>
    <script>
        $(function () {
            $("#slider").responsiveSlides({
                auto: true,
                nav: true,
                speed: 500,
                namespace: "callbacks",
                pager: true,
            });
        });
    </script>
    <div  id="top" class="callbacks_container">
      <ul class="rslides" id="slider">
        <li>
          <div class="banner-text">
            <h3>Lorem Ipsum is   </h3>
            <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC.</p>
          </div>
        </li>
        <li>
          <div class="banner-text">
            <h3>There are many  </h3>
            <p>Popular belief Contrary to , Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC.</p>
          </div>
        </li>
        <li>
          <div class="banner-text">
            <h3>Sed ut perspiciatis</h3>
            <p>Lorem Ipsum is not simply random text. Contrary to popular belief, It has roots in a piece of classical Latin literature from 45 BC.</p>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="content-top">
  <h1>NEW PRODUCTS</h1>
  <div class="grid-in">
    <%= render @product %>
    <div class="clearfix"> </div>
  </div>
</div>

app/views/products/show.html.erb
<!-- grow -->
<div class="grow">
  <div class="container">
    <h2><%= @product.title %></h2>
  </div>
</div>
<!-- grow -->
<div class="product">
  <div class="container">
    <div class="product-price1">
      <div class="top-sing">
        <div class="col-md-7 single-top">
          <div class="flexslider">
            <ul class="slides">
              <li data-thumb="images/si.jpg">
                <div class="thumb-image"> <img src="images/si.jpg" data-imagezoom="true" class="img-responsive"> </div>
              </li>
              <li data-thumb="images/si1.jpg">
                <div class="thumb-image"> <img src="images/si1.jpg" data-imagezoom="true" class="img-responsive"> </div>
              </li>
              <li data-thumb="images/si2.jpg">
                <div class="thumb-image"> <img src="images/si2.jpg" data-imagezoom="true" class="img-responsive"> </div>
              </li>
              <li data-thumb="images/si3.jpg">
                <div class="thumb-image"> <img src="images/si3.jpg" data-imagezoom="true" class="img-responsive"> </div>
              </li>
            </ul>
          </div>
          <div class="clearfix"> </div>
          <!-- slide -->
          <!-- FlexSlider -->
          <script defer src="js/jquery.flexslider.js"></script>
          <link rel="stylesheet" href="css/flexslider.css" type="text/css" media="screen" />
          <script>
              // Can also be used with $(document).ready()
              $(window).load(function() {
                  $('.flexslider').flexslider({
                      animation: "slide",
                      controlNav: "thumbnails"
                  });
              });
          </script>
        </div>
        <div class="col-md-5 single-top-in simpleCart_shelfItem">
          <div class="single-para">
            <h4><%= @product.title %></h4>
            <div class="star-on">
              <div class="review">
                <p><%= @product.author%></p>
              </div>
              <div class="clearfix"> </div>
            </div>
            <h5 class="item_price"><%= number_to_currency(@product.price, unit: "грн.", format: '%n %u') %></h5>
            <p><%= @product.description %></p>
            <a href="#" class="add-cart item_add">ADD TO CART</a>
          </div>
        </div>
        <div class="clearfix"> </div>
      </div>
    </div>
    <div class="clearfix"> </div>
  </div>
</div>